name: platform_info
description: >
  Containts info about current platform
  such as Build mode and Operating system
version: 1.1.1+3
#author: Plague Fox <Plugfox@gmail.com>
homepage: https://github.com/PlugFox/platform_info

#publish_to: 'none' 

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:

dev_dependencies:
  test: any

dependency_overrides:
