name: platform_info
description: >
  Contains info about current platform
  such as Build mode and Operating system
version: 2.0.0-dev
#author: Plague Fox <plugfox@gmail.com>
homepage: https://github.com/PlugFox/platform_info

#publish_to: 'none' 

environment:
  sdk: ">=2.6.0 <3.0.0"

#dependencies:

dev_dependencies:
  test: ^1.15.3
  coverage: ^0.14.0

#dependency_overrides:
