name: platform_info
description: >
  Contains info about current platform
  such as Build mode and Operating system.
version: 4.0.2
repository: https://github.com/PlugFox/platform_info/tree/master
issue_tracker: https://github.com/PlugFox/platform_info/issues
homepage: https://github.com/PlugFox/platform_info
#author: Plague Fox <plugfox@gmail.com>
#documentation: https://pub.dev/documentation/platform_info/latest

funding:
  - https://www.buymeacoffee.com/plugfox
  - https://www.patreon.com/plugfox
  - https://boosty.to/plugfox

topics:
  - platform
  - info
  - cross-platform
  - device
  - information

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

screenshots:
  - description: 'Example of using the library to get the current platform info'
    path: example.png

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  meta: ^1.9.1

dev_dependencies:
  lints: ^2.0.1
  test: ^1.24.2