name: platform_info
description: >
  Contains info about current platform
  such as Build mode and Operating system
version: 2.0.0-dev
author: Plague Fox <plugfox@gmail.com>
repository: https://github.com/PlugFox/platform_info/tree/master
issue_tracker: https://github.com/PlugFox/platform_info/issues
homepage: https://github.com/PlugFox/platform_info
documentation: https://pub.dev/documentation/platform_info/latest

environment:
  sdk: ">=2.6.0 <3.0.0"

dev_dependencies:
  test_coverage: ^0.4.3
  test: ^1.15.3
  pana: ^0.14.2

