name: platform_info
description: >
  Contains info about current platform
  such as Build mode and Operating system.
version: 3.2.0
repository: https://github.com/PlugFox/platform_info/tree/master
issue_tracker: https://github.com/PlugFox/platform_info/issues
homepage: https://github.com/PlugFox/platform_info
#author: Plague Fox <plugfox@gmail.com>
#documentation: https://pub.dev/documentation/platform_info/latest

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  meta: ^1.3.0

dev_dependencies:
  coverage: '>=0.14.2 <2.0.0'
  test: ^1.16.0