name: platform_info
on:
  push:
    branches: [ master, dev, feature/null_safety ]
  pull_request:
    branches: [ master, dev, feature/null_safety ]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: google/dart:dev
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: dart pub get
      - name: Format
        run: dart format --set-exit-if-changed none
      - name: Run analyzer
        run: dart analyze --fatal-infos --fatal-warnings .
      - name: Run tests
        run: dart run test_coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Check Code Coverage
        uses: ChicagoFlutter/lcov-cop@v1.0.2
        with:
          path: coverage/lcov.info
          min_coverage: 95
          exclude: "**/*.g.dart"